version: '3.9'

services:
  web:
    build: .
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
      - ./otp_storage:/var/www/html/otp_storage 
    depends_on:
      - db
    networks:
      - bloom_network
    env_file:
      - .env  


  # MySQL Database
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bloom_basket
      MYSQL_USER: bloomuser
      MYSQL_PASSWORD: bloompassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - bloom_network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_USER: bloomuser
      PMA_PASSWORD: bloompassword
    ports:
      - "8082:80"
    depends_on:
      - db
    networks:
      - bloom_network
  otp-service:
      build:
        context: ./otp-service  # separate folder for OTP code
      ports:
        - "8083:80"  # for local testing
      volumes:
        - ./otp-service:/var/www/html
      environment:
        TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      depends_on:
        - db
      networks:
        - bloom_network
volumes:
  mysql_data:

networks:
  bloom_network:
    driver: bridge
